In [1]:
import torch

here x is the input for the neural network
y is the expected output
w and b are the weights and the biases respectively
z we are doing a matrix multiplication of x and w and then adding it to the bias
finally we are calculating the loss using the binary cross entropy error and we are also getting the logits that is the weights it has finally arrived at after getting the weights
autogtrad is a inbuilt function in torch which allows the automatic computation of the gradients

In [2]:
x=torch.ones(5)
y=torch.zeros(3)
w=torch.randn(5,3,requires_grad=True)
b=torch.randn(3,requires_grad=True)
z=torch.matmul(x,w)+b
loss=torch.nn.functional.binary_cross_entropy_with_logits(z,y)

# Tensor, Functions and Computational graph
here w and b are the parameters which we need to optimize

In [4]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x0000020475133640>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000002045EB63640>


# Computing the gradients
to do backward propagation on loss we call loss.backward() and then we can retrive the values of w and b using the methods w.grad and b.grad

In [5]:
loss.backward()
print(f" the weight are now after doing backpropagation {w.grad}\n The bias {b.grad}")

 the weight are now after doing backpropagation tensor([[0.2788, 0.0011, 0.3297],
        [0.2788, 0.0011, 0.3297],
        [0.2788, 0.0011, 0.3297],
        [0.2788, 0.0011, 0.3297],
        [0.2788, 0.0011, 0.3297]])
 The bias tensor([0.2788, 0.0011, 0.3297])


# Disabiling the Gradient Tracking

In [6]:
z=torch.matmul(x,w)+b
print(z.requires_grad)
with torch.no_grad():
    z=torch.matmul(x,w)+b
print(z.requires_grad)

True
False


using the detach method to remove the tracking of the gradients as they are optimized

In [7]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


# Tensor Gradients and Jacobian

In [8]:
inp=torch.eye(4,5,requires_grad=True)
out=(inp+1).pow(2).t()
out.backward(torch.ones_like(out),retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out),retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out),retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
